apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx_image
          imagePullPolicy: Never
          ports:
            - containerPort: 80
            - containerPort: 443
          livenessProbe:
            exec:
              command:
                - sh
                - /srcs/utils.sh
            initialDelaySeconds: 30
            periodSeconds: 10

              #- containerPort: 22
