#apiVersion: v1
#kind: Service
#metadata:
#  name: phpmyadmin
#  annotations:
#    metallb.universe.tf/allow-shared-ip: shared
#spec:
#  type: LoadBalancer
#  ports:
#  - name: pma
#    port: 5000
#    targetPort: 5000
#  selector:
#    app: pmaPod
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: phpmyadmin-deploy
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: pmaPod
#      type: pmatype
#  template:
#    metadata:
#      name: phpmyadmin-pod
#      labels:
#        app: pmaPod
#        type: pmatype
#    spec:
#      containers: 
#        - name: phpmyadmincontainer
#          image: phpmyadmin_image
#          imagePullPolicy: Never
#          ports:
#            - name: phpmyadmin
#              containerPort: 5000
#          livenessProbe:
#            exec:
#              command:
#                - sh
#                - /srcs/utils.sh
#            initialDelaySeconds: 30
#            periodSeconds: 10
apiVersion: v1
kind: Service
metadata:
  name: service-phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - name: pma
    port: 5000
    targetPort: 5000
  selector:
    app: pmaPod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  template:
    metadata:
      name: phpmyadmin-pod
      labels:
        app: pmaPod
        type: pmatype
    spec:
      containers: 
        - name: phpmyadmincontainer
          image: phpmyadmin_image
          imagePullPolicy: Never
          ports:
            - name: phpmyadmin
              containerPort: 5000
          livenessProbe:
            exec:
              command:
                - sh
                - /srcs/utils.sh
            initialDelaySeconds: 30
            periodSeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: pmaPod
      type: pmatype
