#apiVersion: v1
#kind: Service
#metadata:
#  name: service-wp
#  annotations:
#    metallb.universe.tf/allow-shared-ip: shared
#spec:
#  type: LoadBalancer
#  ports:
#  - name: wordpress
#    port: 5050
#    targetPort: 5050
#  selector:
#      app: wordpressPod
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: wp-deployment
#  labels:
#    app: wordpressPod
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: wordpressPod
#      type: wordpresstype
#  template:
#    metadata:
#      name: wordpress-pod
#      labels:
#        app: wordpressPod
#        type: wordpresstype
#    spec:
#      containers:
#        - name: wordpresscontainer
#          image: wordpress_image
#          imagePullPolicy: Never
#          ports:
#            - name: wordpress
#              containerPort: 5050
#          livenessProbe:
#            exec:
#              command:
#                - sh
#                - /srcs/utils.sh
#            initialDelaySeconds: 30
#            periodSeconds: 10

apiVersion: v1
kind: Service
metadata:
  name: service-wp
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - name: wodpress
    port: 5050
    targetPort: 5050
  selector:
    app: wodpressPod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wodpressPod
    type: wordpresstype
spec:
  template:
    metadata:
      name: wordpressPod
      labels:
        app: wodpressPod
        type: wordpresstype
    spec:
      containers:
        - name: wordpresscontainer
          image: wordpress_image
          imagePullPolicy: Never
          ports:
            - name: wordpress
              containerPort: 5050
          livenessProbe:
            exec:
              command:
                - sh
                - /srcs/utils.sh
            initialDelaySeconds: 30
            periodSeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: wodpressPod
      type: wordpresstype
