apiVersion: v1
kind: Service
metadata:
  name: service-ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - name: port21
    port: 21
    targetPort: 21
  - name: port21000
    port: 21000
    targetPort: 21000
  selector:
    app: ftpsPod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftpsPod
      type: ftps
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftpsPod
        type: ftps
    spec:
      containers: 
        - name: ftpscontainer
          image: ftps_image
          imagePullPolicy: Never
          ports:
            - name: port21
              containerPort: 21
            - name: port21000
              containerPort: 21000
          livenessProbe:
            exec:
              command:
                - sh
                - /srcs/utils.sh
            initialDelaySeconds: 30
            periodSeconds: 10
